---
version: 0.0.1
name: Calc
description: Calculadoras
url: https://sidval.github.io/calc
repository: https://github.com/sidval/calc
timezone: America/Los_Angeles
twitter:
  username: waldd0
# logo: "/img/logo-2x.png"
# google_analytics_id: UA-50755011-1
# google_site_verification: 
#
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
sass:
  style: compressed
exclude:
- ".gitignore"
- CNAME
- readme.md
#
# más info: https://raw.githubusercontent.com/jekyll/jekyll/master/docs/_config.yml
